=== ArtemJJS/XML-Parsing/src/main/resources/data/telecom.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://anelkin.by/telecom"
        xmlns:tns="http://anelkin.by/telecom">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element name="tariff" minOccurs="0" maxOccurs="unbounded" type="tns:tariff"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="tariff">
        <sequence>
            <element name="payRoll" type="tns:positiveDecimal"/>
            <element name="callPrices" type="tns:callPricePlan"/>
            <element name="smsPrice" type="tns:positiveDecimal"/>
            <element name="parameters" type="tns:tariffParameters"/>
        </sequence>
        <attribute name="name" type="string" use="required"/>
        <attribute name="operatorName" type="string" use="required"/>
        <!--attributes are optional by default -->
        <attribute name="openDate" type="date" use="required"/>
        <attribute name="closeDate" type="date"/>
    </complexType>

    <complexType name="callPricePlan">
        <attribute name="insideNetwork" type="tns:positiveDecimal" use="required"/>
        <attribute name="outsideNetwork" type="tns:positiveDecimal" use="required"/>
        <attribute name="onLandLine" type="tns:positiveDecimal" use="required"/>
        <attribute name="onFavoriteNumber" type="tns:positiveDecimal" default="0"/>
    </complexType>

    <complexType name="tariffParameters">
        <attribute name="favoriteNumbersAmount" type="nonNegativeInteger" default="0"/>
        <attribute name="tarification" type="tns:tarificationInterval" default="60"/>
        <attribute name="activationPayment" type="tns:positiveDecimal" default="0"/>
    </complexType>

    <simpleType name="positiveDecimal">
        <restriction base="decimal">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

    <simpleType name="tarificationInterval">
        <restriction base="positiveInteger">
            <enumeration value="1"/>
            <enumeration value="12"/>
            <enumeration value="30"/>
            <enumeration value="60"/>
        </restriction>
    </simpleType>
</schema>

=== ArtemJJS/XML-Parsing/src/main/resources/data/tariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://anelkin.by/telecom telecom.xsd"
         xmlns="http://anelkin.by/telecom">
    <tariff name="Test Tarif 1" operatorName="Velcom" openDate="2015-04-11" closeDate="2017-08-10" id="VL123251">
        <payRoll>14</payRoll>
        <callPrices>
            <insideNetwork>0.1</insideNetwork>
            <outsideNetwork>0.2</outsideNetwork>
            <onLandLine>0.25</onLandLine>
            <onFavoriteNumber>0</onFavoriteNumber>
        </callPrices>
        <smsPrice>0.05</smsPrice>
        <parameters activationPayment="10" favoriteNumbersAmount="3" tarification="12"/>
    </tariff>
    <tariff name="Test Tarif 2" operatorName="Velcom" openDate="2017-01-01" id="VL124122">
        <payRoll>5</payRoll>
        <callPrices>
            <insideNetwork>0</insideNetwork>
            <outsideNetwork>0.5</outsideNetwork>
            <onLandLine>0.5</onLandLine>
        </callPrices>
        <smsPrice>0.1</smsPrice>
        <parameters/>
    </tariff>
</tariffs>

=== ArtemJJS/XML-Parsing/src/main/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="telecom.xsd"
        xmlns="http://anelkin.by/telecom">
    <tariff name="Test Tarif 1" operatorName="Velcom">
        <payRoll>14</payRoll>
        <callPrices onFavoriteNumber="0.05">
            <insideNetwork>0.1</insideNetwork>
            <outsideNetwork>0.2</outsideNetwork>
            <onLandLine>0.25</onLandLine>
        </callPrices>
        <smsPrice>0.05</smsPrice>
        <parameters>
            <favoriteNumbersAmount>3</favoriteNumbersAmount>
            <tarificatoin>12</tarificatoin>
            <activationPayment>9.99</activationPayment>
        </parameters>
    </tariff>
</tariffs>
